### ISSUE TITLE
Ethernet port

### ISSUE THREAD

**Issue by adminy** [PTS93/Minimal-RPi-CM-4-Carrier#1]
I think it's really amazing how minimal this is! However, isn't an ethernet port more useful than usb and hdmi & sd combined? 

with an ethernet port, you have network boot, ssh which is more useful than having a screen, especially on a raspberry pi. Also any resource can be downloaded and stored in ram. 

So waiting for the simplest yet design which will be just a single ethernet port that delivers everything else

**Comment by timonsku** [comment]
This is just a data dump for a quick and dirty demonstration. I might make another more properly made educational board later on that will integrate Ethernet but this board here will see no changes.
